[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPHSL = "7fb6135f-58fe-4112-84ca-653cf5be0c77"
MadNLPMumps = "3b83494e-c0a4-4895-918b-9157a7a085a1"
MadNLPTests = "b52a2a03-04ab-4a5f-9698-6a2deff93217"
MathOptAI = "e52c2cb8-508e-4e12-9dd2-9c4755b60e73"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgIncidence = "892fab00-3092-4bd0-9c46-66676a93f84e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
MathProgIncidence = "0.3"
